# Generated by Django 3.2.5 on 2021-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('dxCode', models.CharField(blank=True, max_length=200)),
                ('phone', models.IntegerField(blank=True, default=1)),
                ('subject', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
