# Generated by Django 3.2.5 on 2021-08-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='Resumes',
        ),
    ]
