# Generated by Django 3.2.5 on 2021-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='dxCode',
        ),
        migrations.AddField(
            model_name='contact',
            name='resume',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
