# Generated by Django 3.2.5 on 2021-08-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_resume_resumes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resumes',
            new_name='Resume',
        ),
    ]
